import{a as f,i as o,S as h}from"./assets/vendor-Dy2ZTtfi.js";(function(){const n=document.createElement("link").relList;if(n&&n.supports&&n.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))e(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const c of r.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&e(c)}).observe(document,{childList:!0,subtree:!0});function s(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function e(t){if(t.ep)return;t.ep=!0;const r=s(t);fetch(t.href,r)}})();const u="51358169-fa0c0ba6de1b0bb5150f64058",y="https://pixabay.com/api/";async function w(i){var s;if(!i||i.trim()==="")throw new Error("Search query cannot be empty");const n={key:u,q:i.trim(),image_type:"photo",orientation:"horizontal",safesearch:"true",per_page:40};try{const e=await f.get(y,{params:n});if(!e.data||!Array.isArray(e.data.hits))throw new Error("Invalid response from Pixabay API");return e.data}catch(e){if(e.response){const t=e.response.status,r=((s=e.response.data)==null?void 0:s.error)||e.message;switch(t){case 400:throw new Error("Invalid search parameters");case 403:throw new Error("Invalid API key or access denied");case 429:throw new Error("Rate limit exceeded. Please try again later");default:throw new Error(`Pixabay API error: ${t} - ${r}`)}}else throw e.request?new Error("Network error: Unable to connect to Pixabay API"):new Error(`Error: ${e.message}`)}}const l=document.querySelector(".gallery"),m=document.querySelector(".loader");l||(o.error({title:"Gallery not found",message:'Element with class "gallery" is missing from the page.',position:"topRight"}),console.error("Gallery element not found!"));m||(o.error({title:"Loader not found",message:'Element with class "loader" is missing from the page.',position:"topRight"}),console.error("Loader element not found!"));let p;try{p=new h(".gallery a",{captionsData:"alt",captionDelay:250})}catch(i){o.error({title:"Lightbox Error",message:`Failed to initialize lightbox: ${i.message}`,position:"topRight"}),console.error("SimpleLightbox initialization error:",i)}function b(i){if(!Array.isArray(i)||i.length===0){o.info({title:"No Images",message:"No images found to display.",position:"topRight"}),console.warn("No images to display");return}const n=i.map(({webformatURL:s,largeImageURL:e,tags:t,likes:r,views:c,comments:g,downloads:d})=>`
      <li class="gallery-item">
        <a href="${e}">
          <img src="${s}" alt="${t}" class="gallery-image" loading="lazy">
        </a>
        <div class="info">
          <p class="info-item"><b>Likes:</b> ${r}</p>
          <p class="info-item"><b>Views:</b> ${c}</p>
          <p class="info-item"><b>Comments:</b> ${g}</p>
          <p class="info-item"><b>Downloads:</b> ${d}</p>
        </div>
      </li>`).join("");l==null||l.insertAdjacentHTML("beforeend",n);try{p==null||p.refresh()}catch(s){o.warning({title:"Lightbox Update Failed",message:"Unable to refresh image preview.",position:"topRight"}),console.error("Lightbox refresh error:",s)}}function L(){l?l.innerHTML="":o.warning({title:"Gallery Missing",message:"Cannot clear gallery — element is missing.",position:"topRight"})}function R(){m?m.classList.remove("is-hidden"):o.warning({title:"Loader Missing",message:"Cannot show loader — element is missing.",position:"topRight"})}function E(){m?m.classList.add("is-hidden"):o.warning({title:"Loader Missing",message:"Cannot hide loader — element is missing.",position:"topRight"})}const a=document.querySelector(".form");a||(o.error({title:"Form Missing",message:'Form element with class "form" not found on the page.',position:"topRight"}),console.error("Form element not found!"));o.settings({timeout:5e3,resetOnHover:!0,icon:"material-icons",transitionIn:"flipInX",transitionOut:"flipOutX"});a==null||a.addEventListener("submit",async i=>{i.preventDefault();const n=a.elements["search-text"];if(!n){o.error({title:"Input Missing",message:'Search input field with name="search-text" not found.',position:"topRight"}),console.error("Search input not found!");return}const s=n.value.trim();if(!s){o.warning({title:"Empty Input",message:"Search input must not be empty!",position:"topRight"});return}L(),R();try{const e=await w(s);if(!e||!e.hits)throw new Error("Unexpected response structure from API.");e.hits.length===0?o.error({title:"No Results",message:"No images match your search. Please try another keyword.",position:"topRight"}):(b(e.hits),o.success({title:"Success",message:`Found ${e.totalHits} images.`,position:"topRight"}))}catch(e){console.error("Search error:",e),o.error({title:"Request Failed",message:`Something went wrong: ${e.message}`,position:"topRight"})}finally{E(),a.reset()}});
//# sourceMappingURL=index.js.map
