import{a as A,S as N,i as n}from"./assets/vendor-BDlA6vKe.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const l of t.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&i(l)}).observe(document,{childList:!0,subtree:!0});function s(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function i(e){if(e.ep)return;e.ep=!0;const t=s(e);fetch(e.href,t)}})();const b=document.getElementById("scrollToTop");window.addEventListener("scroll",()=>{window.scrollY>400?b.classList.remove("is-hidden"):b.classList.add("is-hidden")});b.addEventListener("click",()=>{window.scrollTo({top:0,behavior:"smooth"})});const P="51358169-fa0c0ba6de1b0bb5150f64058",T="https://pixabay.com/api/",x=15;async function w(o,r=1){var i,e;if(!o||o.trim()==="")throw new Error("Search query cannot be empty");const s={key:P,q:o.trim(),image_type:"photo",orientation:"horizontal",safesearch:"true",per_page:x,page:r};try{return(await A.get(T,{params:s})).data}catch(t){throw new Error(((e=(i=t.response)==null?void 0:i.data)==null?void 0:e.error)||t.message)}}const m=document.querySelector(".gallery"),a=document.querySelector(".loader"),c=document.querySelector(".load-more");let p;try{p=new N(".gallery a",{captionsData:"alt",captionDelay:250})}catch(o){n.error({title:"Lightbox Error",message:`Failed to initialize lightbox: ${o.message}`,position:"topRight"})}function v(o){if(!Array.isArray(o)||o.length===0){n.info({title:"No Images",message:"No images found to display.",position:"topRight"});return}const r=o.map(({webformatURL:s,largeImageURL:i,tags:e,likes:t,views:l,comments:I,downloads:q})=>`
      <li class="gallery-item">
        <a href="${i}">
          <img src="${s}" alt="${e}" class="gallery-image" loading="lazy">
        </a>
        <div class="info">
          <p class="info-item"><b>Likes:</b> ${t}</p>
          <p class="info-item"><b>Views:</b> ${l}</p>
          <p class="info-item"><b>Comments:</b> ${I}</p>
          <p class="info-item"><b>Downloads:</b> ${q}</p>
        </div>
      </li>`).join("");m==null||m.insertAdjacentHTML("beforeend",r);try{p==null||p.refresh()}catch{n.warning({title:"Lightbox Update Failed",message:"Unable to refresh image preview.",position:"topRight"})}}function O(){m&&(m.innerHTML="")}function R(){a==null||a.classList.remove("is-hidden")}function S(){a==null||a.classList.add("is-hidden")}function E(){c==null||c.classList.remove("is-hidden")}function L(){c==null||c.classList.add("is-hidden")}const d=document.querySelector(".form"),y=document.querySelector(".load-more");let h="",g=1,f=0,u=0;d==null||d.addEventListener("submit",async o=>{if(o.preventDefault(),h=d.elements["search-text"].value.trim(),g=1,u=0,!h){n.warning({title:"Empty Input",message:"Search input must not be empty!",position:"topRight"});return}O(),L(),R();try{const s=await w(h,g);f=s.totalHits;const i=s.hits;if(i.length===0){n.info({title:"No Results",message:"No images found. Try another keyword.",position:"topRight"});return}v(i),u+=i.length,n.success({title:"Success",message:`Found ${f} images.`,position:"topRight"}),u<f&&E()}catch(s){n.error({title:"Error",message:s.message,position:"topRight"})}finally{S(),d.reset()}});y==null||y.addEventListener("click",async()=>{g+=1,R(),L();try{const r=(await w(h,g)).hits;v(r),u+=r.length;const s=document.querySelector(".gallery-item"),i=(s==null?void 0:s.getBoundingClientRect().height)||200;window.scrollBy({top:i*2,behavior:"smooth"}),u>=f?(L(),n.info({title:"End of Results",message:"We're sorry, but you've reached the end of search results.",position:"topRight"})):E()}catch(o){n.error({title:"Load Failed",message:o.message,position:"topRight"})}finally{S()}});
//# sourceMappingURL=index.js.map
